monolog:
    channels: [ 'product' ]

    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        product:
            type: stream
            path: '%kernel.logs_dir%/product.log'
            level: debug
            channels: [ 'product' ]
