name: product_api
services:
    php:
        build:
            context: ./php
        container_name: product-api-php
        volumes:
            - ../:/var/www/html
        working_dir: /var/www/html
        environment:
            APP_ENV: dev
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: product-api-nginx
        ports:
            - "8080:80"
        volumes:
            - ../public:/var/www/html/public
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    db:
        image: mysql:8.4
        container_name: product-api-db
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
