services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
    App\EventListener\ProductListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
